{% set name = "feast" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/feast-{{ version }}.tar.gz
  sha256: ae67776c607d89b14e49d771cd61c4405c163469b73803db19dea34cdd67554c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bowler
    - click <9.0.0,>=7.0.0
    - colorama <1,>=0.3.9
    - dask-core <2022.02.0,>=2021.*
    - dill ==0.3.*
    - fastapi <1,>=0.68.0
    - fastavro <2,>=1.1.0
    - google-api-core <3,>=1.23.0
    - googleapis-common-protos <2,>=1.52.*
    - grpcio <2,>=1.47.0
    - grpcio-reflection <2,>=1.47.0
    - jinja2 <4,>=2
    - jsonschema
    - mmh3
    - numpy <3,>=1.22
    - pandas <2,>=1.4.3
    - pandavro ==1.5.*
    - proto-plus <2,>=1.20.0
    - protobuf <4,>3.20
    - pyarrow <9,>=4
    - pydantic <2,>=1
    - pygments <3,>=2.12.0
    - python >=3.7
    - pyyaml <7,>=5.4.*
    - sqlalchemy <2,>1
    - tabulate <1,>=0.8.0
    - tenacity <9,>=7
    - tensorflow-metadata <2.0.0,>=1.0.0
    - toml <1,>=0.10.0
    - tqdm <5,>=4
    - typeguard
    - uvicorn <1,>=0.14.0

test:
  imports:
    - feast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/feast-dev/feast
  summary: Python SDK for Feast
  license: Apache-2.0 & MIT & LGPL-2.1
  license_file:
    - LICENSE
    - .eggs/setuptools_scm-7.0.5-py3.10.egg/EGG-INFO/LICENSE
    - .eggs/grpcio-1.47.0-py3.10-linux-x86_64.egg/EGG-INFO/LICENSE
    - .eggs/mypy_protobuf-3.1.0-py3.10.egg/EGG-INFO/LICENSE
    - .eggs/PyBindGen-0.22.0-py3.10.egg/EGG-INFO/COPYING

extra:
  recipe-maintainers:
    - bgalvao
