{% set name = "rai-core-flask" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rai_core_flask-{{ version }}.tar.gz
  sha256: eb34ce72929291db17478a98a2bdfe81e4b49bf21014e2b6a3fb0948abc882eb

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - flask
    - flask-cors
    - gevent ==21.12.0
    - greenlet ==1.1.2
    - ipython ==7.16.3  # [py<=36]
    - itsdangerous ==2.0.1
    - markupsafe <2.1.0
    - python
    - werkzeug <2.1.0

test:
  imports:
    - rai_core_flask
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/rai-core-flask/
  summary: Responsible AI Core Flask Wrapper
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
    - bgalvao
