{% set name = "rai-core-flask" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rai_core_flask-{{ version }}.tar.gz
  sha256: 5498b8c6beabd690d58d4038e833f62e92976e9fc55dba9c319d483d41bf4585

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - flask >=1.1.0,==1.1.*
    - flask-cors ==3.0.10
    - gevent ==21.12.0
    - greenlet ==1.1.2
    - ipython ==7.16.3  # [py<=36]
    - itsdangerous ==2.0.1
    - jinja2 ==2.11.3
    - markupsafe <2.1.0
    - python
    - werkzeug <2.1.0

test:
  imports:
    - rai_core_flask
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/rai-core-flask/
  summary: Responsible AI Core Flask Wrapper
  license: MIT

extra:
  recipe-maintainers:
    - bgalvao
    - janjagusch
