{% set name = "featureform" %}
{% set version = "1.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/featureform-{{ version }}.tar.gz
  sha256: f5b1cb4865fdc1dea30dad8a10923f701b4aa6c2ed611d4d8a732f2dcae69bc4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.1.2
    - dataclasses ==0.6
    - flask ==2.2.1
    - flask-cors ==3.0.10
    - grpcio ==1.47.0
    - numpy ==1.21.6
    - pandas ==1.3.5
    - pandasql >=0.7.3
    - protobuf >=3.17.3
    - pyspark >=3.3.0
    - python >=3.7
    - typeguard >=2.7.1
    - typing-extensions >=4.1.1

test:
  imports:
    - featureform
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://featureform.com
  summary: Package for the Featureform Feature Store
  license: MPL-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - bgalvao
