{% set name = "raiwidgets" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/raiwidgets-{{ version }}.tar.gz
  sha256: 6ddfc29e8c1a09b82a3960ded00e2b6272c043fb0b73ff8f0152eef960acc5a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - erroranalysis >=0.3.2
    - fairlearn >=0.7.0
    - itsdangerous
    - jinja2
    - lightgbm >=2.0.11
    - numpy >=1.17.2
    - pandas >=0.25.1
    - python >=3.6
    - rai-core-flask ==0.3.0
    - responsibleai ==0.19.0
    - scikit-learn >=0.22.1
    - scipy >=1.4.1

test:
  imports:
    - raiwidgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/responsible-ai-widgets
  summary: Interactive visualizations to assess fairness, explain models, generate counterfactual examples, analyze causal effects and analyze errors in Machine Learning models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgalvao
    - janjagusch
