{% set name = "responsibleai" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/responsibleai-{{ version }}.tar.gz
  sha256: dde6dc93e8d73e74170df0322071003c79a872ea606f38b9d76d52c891751b1a

build:
  noarch: python
  script: touch requirements.txt && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dice-ml >=0.8
    - econml >=0.12.0
    - erroranalysis >=0.3.2
    - interpret-community >=0.25.0
    - ipykernel <=6.6.0
    - jsonschema
    - lightgbm >=2.0.11
    - markupsafe <2.1.0
    - networkx <=2.5
    - numba <0.54.0
    - numpy >=1.17.2
    - pandas >=0.25.1
    - python >=3.6
    - raiutils >=0.1.0
    - scikit-learn <1.1,>=0.22.1
    - scipy >=1.4.1
    - semver >=2.13.0

test:
  imports:
    - responsibleai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/responsible-ai-toolbox
  summary: SDK API to explain models, generate counterfactual examples, analyze causal effects and analyze errors in Machine Learning models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgalvao
    - janjagusch
