{% set name = "interpret-community" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/interpret_community-{{ version }}.tar.gz
  sha256: 372ca3d301c98f6627b5358f9e6f2c0e07f9c0ef8cdafb2fdb3d211ae16fbccc

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - interpret-core >=0.1.20,<=0.2.7
    - ml-wrappers ==0.2.0
    - numpy
    - packaging
    - pandas
    - python >=3.6
    - scikit-learn
    - scipy
    - shap >=0.20.0,<=0.40.0

test:
  imports:
    - interpret_community
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/interpretml/interpret-community
  summary: Microsoft Interpret Extensions SDK for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgalvao
    - janjagusch
