{% set name = "interpret-core" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/interpret-core-{{ version }}.tar.gz
  sha256: b0b0b9aed8214fc1c0e3c400eafd663db4d37dfd285d202d8339886c44e1b901

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python >=3.6
    - wheel
    - compilers
  run:
    - python >=3.6
    - joblib
    - numpy
    - pandas
    - scipy

test:
  imports:
    - interpret
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable machine learning models. Explain blackbox machine learning.
  license: MIT
  license_file: symbolic/LICENSE

extra:
  recipe-maintainers:
    - bgalvao
    - janjagusch
